### ISSUE TITLE
New update breaks fumo

### ISSUE THREAD

**Issue by VilcsiTH** [DestroyedClone/FMPModelSwap#1]
The update that was released with the DLC sadly turns the Cirno Fumo back to the normal Commando model.
I've included a log and an image showing the mod and equipment active, to (hopefully) help in returning the Fumo to its righteous place.
The log was taken with a Loader, with the Command artifact active. The equipment was activated twice, and I grabbed a Defiant Gouge before the 2nd activation.
![forgivecommando](https://user-images.githubusercontent.com/7689214/157229244-78f2c27a-d8d3-4766-8c49-216b49c0f338.png)

[fumopls.log](https://github.com/DestroyedClone/FMPModelSwap/files/8205682/fumopls.log)

**Comment by DestroyedClone** [comment]
Fixed with patch https://github.com/DestroyedClone/FMPModelSwap/commit/bf30bfff181e0c417f8c487e55eb369d19fbe43b
Thunderstore release soonish
